generator:
  class: sfPropelGenerator
  param:
    model_class:           Cre8MenuType
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cre8_menu_type
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display:           [=name]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
