<?php


/**
 * Skeleton subclass for performing query and update operations on the 'cre8_menu_content_type_flash' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * wto, 23 lut 2010, 13:09:40
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.cre8PropelMenuPlugin.lib.model
 */
class cre8MenuContentTypeFlashPeer extends Plugincre8MenuContentTypeFlashPeer {

} // cre8MenuContentTypeFlashPeer
