<?php


/**
 * Skeleton subclass for representing a row from the 'cre8_menu_type' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * wto, 23 lut 2010, 13:09:39
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.cre8PropelMenuPlugin.lib.model
 */
class cre8MenuType extends Plugincre8MenuType {

} // cre8MenuType
