<?php


/**
 * Skeleton subclass for performing query and update operations on the 'cre8_menu_content_view_permission' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * śro, 17 mar 2010, 11:47:26
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.cre8PropelMenuPlugin.lib.model
 */
class cre8MenuContentViewPermissionPeer extends Basecre8MenuContentViewPermissionPeer {

} // cre8MenuContentViewPermissionPeer
