<?php


/**
 * Skeleton subclass for representing a row from the 'cre8_content_type' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * wto, 23 lut 2010, 13:09:39
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.cre8PropelMenuPlugin.lib.model
 */
class cre8ContentType extends Plugincre8ContentType {
  public function __toString()
  {
    return $this->getName();
  }

  /**
	 * Initializes internal state of cre8ContentType object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // cre8ContentType
